### ISSUE TITLE
available for any file format?

### ISSUE THREAD

**Issue by KyawNaingTun** [prachiFam/amazon_s3_cognito#1]
Hi @prachiFam ,
Appreciate for your effort. Can I upload other file format like (.pdf, docx, xls, etc)?

**Comment by prachiFam** [comment]
Yes. We have not tried to upload another file formats. But they surely must
work too.
------------------------------
[image: FAM Properties] <http://dubai.famproperties.com/>
Prachi Saxena
Mobile Applications Developer
T: (+971) 4 369 1700  <+97143691700>
F: (+971) 4 447 3572
Building 13, Office 303 & 304
Bay Square - Business Bay
Burj Khalifa District
P.O Box 215088
Dubai, UAE
*fäm*Properties.com <http://dubai.famproperties.com/>
Location Map
<https://www.google.com/maps/place/f%C3%A4m+Properties+-+Dubai+Real+Estate+Brokers/@25.1870084,55.2816753,17z/data=!4m2!3m1!1s0x0000000000000000:0x64b7bc4ca8ecb767?hl=en-US>

*Stay Connected*
[image: Facebook] <https://www.facebook.com/famproperties>   [image:
LinkedIn] <http://www.linkedin.com/in/famproperties>   [image: Twitter]
<https://twitter.com/famproperties12>   [image: Youtube]
<http://www.youtube.com/user/famproperties123>   [image: Blog]
<http://blog.famproperties.com/>   [image: Plus]
<https://plus.google.com/+Famproperties2>

**Comment by KyawNaingTun** [comment]
Thanks @prachiFam

**Comment by prachiFam** [comment]
This issue is closed. Kindly reopen in case some file format is not uploading
