### ISSUE TITLE
How to configure Cognito?

### ISSUE THREAD

**Issue by joaogalli** [prachiFam/amazon_s3_cognito#10]
Hi guys,

could help by providing more basic information on how to configure Cognito for simply uploading to S3?
For example, how do I get this IDENTITY_POOL_ID ?

A third party article would help also. Thanks.

**Comment by andrewpmoore** [comment]
I'm too struggling with this. I've followed the section here on aws' site:
https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-identity-pool.html

I've got the pool id, but I'm not sure I've other stuff set up correctly as I can't upload

**Comment by ringonotts** [comment]
For when i forget this next time around...

I've got public access working by following this link https://www.studytutorial.in/android-application-integrate-to-amazon-s3-tutorial

However, AWS has changed so its not the same now. You have to add an "Allowed Service" for S3 in your unauth bucket role. There is no need to enter the ARN now.

**Comment by prachiFam** [comment]
Use the above-mentioned link to configure the AWS config properly. This is not a library issue so closing this for now.
 https://www.studytutorial.in/android-application-integrate-to-amazon-s3-tutorial
