### ISSUE TITLE
Identity pool id not found error 400

### ISSUE THREAD

**Issue by aashaykapoor** [prachiFam/amazon_s3_cognito#17]
Every time I try working with this, I am getting this error:

❌ upload failed
E/AwsRegionHelper(30895): error in upload id [ 17 ] : IdentityPool XXX' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID:XXXXX)

This is my code snippet:

  String uploadedImageUrl = await AmazonS3Cognito.upload(
            info.path,
           "whg-needy-jobvideos",
              "ap-south-1:e7348acd-23ec-42cd-8094-fXX6febXXXX",
            "myImage",     
            "ap-south-1",
            "ap-south-1",
            );

I do not know where can I get the sub-region and that's why used the region in sub-region field.

**Comment by prachiFam** [comment]
Hi,

You can use android logcat to view the full failure message on amazon. If subregion is wrong, amazon will give you the rigth sub-region.

Also on your AWS console look closely you could find sub-region.

**Comment by prachiFam** [comment]
Since this is not library specific issue, we are closing the issue.
