### ISSUE TITLE
not able to build in xcode 12.2

### ISSUE THREAD

**Issue by tushardubey121** [prachiFam/amazon_s3_cognito#19]
Not able to build the code it return the framework error.
Flutter version 1.22.2
Xcode version 12.2
Simulator OS version  14.2

**Comment by bperreault** [comment]
Not sure if this is helpful, but the version at Prasso works in XCode 12 for me. https://github.com/prasso/amazon_s3_cognito

**Comment by tushardubey121** [comment]
Please check with xCode 12.2 
`error: cannot find 'AWSS3TransferManagerUploadRequest' in scope
                  let uploadRequest = AWSS3TransferManagerUploadRequest()`
                  
`error: cannot find 'AWSS3TransferManager' in scope
                  AWSS3TransferManager.default().upload(uploadRequest!).continueWith { (task) -> AnyObject? in`
                  
`error: cannot find 'AWSS3TransferManagerUploadRequest' in scope
              let uploadRequest = AWSS3TransferManagerUploadRequest()      `

**Comment by bperreault** [comment]
I use Version 12.3 (12C33).
to me, that sounds like a need to make sure the AWS references got pod installed. not xCode 12.2 issue

**Comment by imkrishnaagrawal** [comment]
I am facing the same issue

**Comment by bperreault** [comment]
There's a PR may be helpful.  just came in today. https://github.com/prachiFam/amazon_s3_cognito/pull/21

**Comment by prachiFam** [comment]
PR is merged into the repo. Hence this issue is fixed now.
