### ISSUE TITLE
IDENTITY_POOL_ID ? what it is?

### ISSUE THREAD

**Issue by SunryTeang** [prachiFam/amazon_s3_cognito#2]

**Comment by prachiFam** [comment]
Kindly refer to [this](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html)  document 


A well-written [tutorial](https://grokonez.com/android/uploaddownload-files-images-amazon-s3-android) that will help you configure the AWS configurations.

**Comment by prachiFam** [comment]
Closing this issue for time being. Kindly reopen if anyone is facing configuration error.
