### ISSUE TITLE
The plugins `amazon_s3_cognito,` use a deprecated version of the Android embedding. To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs. If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

### ISSUE THREAD

**Issue by rohitrvayuz** [prachiFam/amazon_s3_cognito#24]
The plugins `amazon_s3_cognito` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by rohitrvayuz** [comment]
I am getting this error on flutter 2.5.2

**Comment by prachiFam** [comment]
At the moment this is just a warning thrown by android. To get rid of this you can use v2embedding branch at the moment. The branch is under testing and a newer version will be release as soon as we test properly our new branch code. 

You can use like this:-

amazon_s3_cognito:
    git:
      url: https://github.com/prachiFam/amazon_s3_cognito.git
      ref: v2embedding

**Comment by rohitrvayuz** [comment]
@prachiFam  Thank you.
